In [2]:
import akshare as ak

In [3]:
ak.fund_name_em()

,基金代码,拼音缩写,基金简称,基金类型,拼音全称
0,000001,HXCZHH,华夏成长混合,混合型-灵活,HUAXIACHENGZHANGHUNHE
1,000002,HXCZHH,华夏成长混合(后端),混合型-灵活,HUAXIACHENGZHANGHUNHE
2,000003,ZHKZZZQA,中海可转债债券A,债券型-混合二级,ZHONGHAIKEZHUANZHAIZHAIQUANA
3,000004,ZHKZZZQC,中海可转债债券C,债券型-混合二级,ZHONGHAIKEZHUANZHAIZHAIQUANC
4,000005,JSZQXYDQZQ,嘉实增强信用定期债券,债券型-混合一级,JIASHIZENGQIANGXINYONGDINGQIZHAIQUAN
...,...,...,...,...,...
26354,970192,XZZGJQLXJTLHB,兴证资管金麒麟现金添利货币,货币型-普通货币,XINGZHENGZIGUANJINQILINXIANJINTIANLIHUOBI
26355,970194,XZZGJQL3GYFOFA,兴证资管金麒麟3个月(FOF)A,FOF-进取型,XINGZHENGZIGUANJINQILIN3GEYUEFOFA
26356,970195,XZZGJQL3GYFOFC,兴证资管金麒麟3个月(FOF)C,FOF-进取型,XINGZHENGZIGUANJINQILIN3GEYUEFOFC
26357,970204,XZZGJQLXXZLLGYCYQZQA,兴证资管金麒麟兴享增利六个月持有期债券A,债券型-混合二级,XINGZHENGZIGUANJINQILINXINGXIANGZENGLILIUGEYUE...
26358,970205,XZZGJQLXXZLLGYCYQZQC,兴证资管金麒麟兴享增利六个月持有期债券C,债券型-混合二级,XINGZHENGZIGUANJINQILINXINGXIANGZENGLILIUGEYUE...

In [10]:
ak.fund_open_fund_daily_em()

,基金代码,基金简称,2026-03-31-单位净值,2026-03-31-累计净值,2026-03-30-单位净值,2026-03-30-累计净值,日增长值,日增长率,申购状态,赎回状态,手续费
0,011598,信澳医药健康混合A,1.2004,1.2004,1.1623,1.1623,0.0381,3.28,限大额,开放赎回,0.15%
1,024171,信澳医药健康混合C,1.1957,1.1957,1.1578,1.1578,0.0379,3.27,限大额,开放赎回,0.00%
2,161226,国投瑞银白银期货(LOF)A,2.0411,2.0411,1.9832,1.9832,0.0579,2.92,暂停申购,开放赎回,0.10%
3,019005,国投瑞银白银期货(LOF)C,2.0214,2.0214,1.964,1.964,0.0574,2.92,暂停申购,开放赎回,0.00%
4,024172,信澳中小盘混合C,1.748,1.748,1.702,1.702,0.046,2.70,开放申购,开放赎回,0.00%
...,...,...,...,...,...,...,...,...,...,...,...
22993,026987,汇泉科创创业量化选股混合C,,,,,,,暂停申购,暂停赎回,0.00%
22994,026934,鑫元周期睿选混合发起式C,,,,,,,暂停申购,暂停赎回,0.00%
22995,026933,鑫元周期睿选混合发起式A,,,,,,,暂停申购,暂停赎回,0.08%
22996,026677,创金合信弘达债券C,,,,,,,封闭期,封闭期,0.00%
22997,026676,创金合信弘达债券A,,,,,,,封闭期,封闭期,0.03%

In [48]:
ak.fund_open_fund_info_em(symbol='002207', indicator="单位净值走势")

            净值日期   单位净值    日增长率
0     2015-12-02  1.000  0.0000
1     2015-12-03  1.003  0.3000
2     2015-12-04  1.003  0.0000
3     2015-12-07  1.004  0.0997
4     2015-12-08  1.003 -0.0996
...          ...    ...     ...
2513  2026-03-27  2.793  2.8400
2514  2026-03-30  2.881  3.1500
2515  2026-03-31  2.883  0.0700
2516  2026-04-01  2.950  2.3200
2517  2026-04-02  2.863 -2.9500

[2518 rows x 3 columns]

In [45]:
ak.fund_open_fund_info_em(symbol='002207', indicator="累计净值走势")

            净值日期   累计净值
0     2015-12-02  1.000
1     2015-12-03  1.003
2     2015-12-04  1.003
3     2015-12-07  1.004
4     2015-12-08  1.003
...          ...    ...
2513  2026-03-27  2.793
2514  2026-03-30  2.881
2515  2026-03-31  2.883
2516  2026-04-01  2.950
2517  2026-04-02  2.863

[2518 rows x 2 columns]

In [14]:
ak.fund_value_estimation_em('全部')

,序号,基金代码,基金名称,2026-03-31-估算数据-估算值,2026-03-31-估算数据-估算增长率,2026-03-31-公布数据-单位净值,2026-03-31-公布数据-日增长率,估算偏差,2026-03-30-单位净值
0,1,025486,中邮新锐量化选股混合发起式A,1.1054,3.43%,1.0557,-1.22%,4.65%,1.0687
1,2,025487,中邮新锐量化选股混合发起式C,1.1028,3.43%,1.0532,-1.22%,4.65%,1.0662
2,3,025447,万家元晟量化选股混合发起式A,1.2101,3.32%,1.1529,-1.57%,4.89%,1.1713
3,4,025448,万家元晟量化选股混合发起式C,1.2069,3.32%,1.1498,-1.58%,4.90%,1.1682
4,5,011598,信澳医药健康混合A,1.1977,3.05%,1.2004,3.28%,-0.23%,1.1623
...,...,...,...,...,...,...,...,...,...
19995,19996,000524,摩根民生需求股票A,2.5138,-2.09%,2.4880,-3.10%,1.01%,2.5676
19996,19997,000603,易方达创新驱动灵活配置混合,2.3469,-2.09%,2.3200,-3.21%,1.12%,2.3970
19997,19998,010264,鹏华成长智选混合A,1.0263,-2.09%,1.0262,-2.10%,0.01%,1.0482
19998,19999,011488,申万菱信乐享混合A,1.5082,-2.09%,1.5020,-2.49%,0.40%,1.5403
19999,20000,011668,东财高端制造增强C,1.1548,-2.09%,1.1552,-2.05%,-0.04%,1.1794

In [44]:
ak.fund_portfolio_hold_em('002207', '2025')

    序号    股票代码  股票名称  占净值比例      持股数      持仓市值              季度
0    1  601069  西部黄金   9.34   986.83  16618.22  2025年1季度股票投资明细
1    2  600988  赤峰黄金   9.16   711.29  16288.47  2025年1季度股票投资明细
2    3  601899  紫金矿业   8.73   857.09  15530.38  2025年1季度股票投资明细
3    4  000975  山金国际   8.73   808.26  15518.58  2025年1季度股票投资明细
4    5  600547  山东黄金   8.48   561.00  15079.63  2025年1季度股票投资明细
5    6  600489  中金黄金   7.99  1010.12  14212.43  2025年1季度股票投资明细
6    7  002237  恒邦股份   7.99  1252.83  14207.05  2025年1季度股票投资明细
7    8  600961  株冶集团   7.82  1458.18  13911.04  2025年1季度股票投资明细
8    9  002155  湖南黄金   7.73   601.18  13749.02  2025年1季度股票投资明细
9   10  000603  盛达资源   7.73   875.84  13741.99  2025年1季度股票投资明细
10  11  601899  紫金矿业   9.22   911.34  17771.03  2025年2季度股票投资明细
11  12  600547  山东黄金   8.88   536.05  17116.23  2025年2季度股票投资明细
12  13  002155  湖南黄金   8.79   949.58  16949.95  2025年2季度股票投资明细
13  14  000975  山金国际   8.73   888.35  16825.34  2025年2季度股票投资明细
14  15  600489  中金黄金   8.63  1136.57  16627.97  2025年2季度股票投资明细
15  16  600988  赤峰黄金   8.52   660.34  16429.38  2025年2季度股票投资明细
16  17  600961  株冶集团   8.15  1406.00  15719.08  2025年2季度股票投资明细
17  18  000426  兴业银锡   8.07   984.12  15549.10  2025年2季度股票投资明细
18  19  000603  盛达资源   7.79  1008.58  15017.81  2025年2季度股票投资明细
19  20  601069  西部黄金   7.69   728.44  14823.76  2025年2季度股票投资明细
20  21  000506  招金黄金   4.96   973.03   9555.15  2025年2季度股票投资明细
21  22  001337  四川黄金   3.08   245.37   5945.32  2025年2季度股票投资明细
22  23  000426  兴业银锡   9.32   943.82  31042.25  2025年3季度股票投资明细
23  24  601899  紫金矿业   9.20  1040.18  30622.89  2025年3季度股票投资明细
24  25  600489  中金黄金   9.06  1375.04  30154.65  2025年3季度股票投资明细
25  26  000603  盛达资源   8.91  1121.69  29657.58  2025年3季度股票投资明细
26  27  600988  赤峰黄金   8.88   999.06  29552.34  2025年3季度股票投资明细
27  28  002155  湖南黄金   8.47  1256.08  28186.38  2025年3季度股票投资明细
28  29  600961  株冶集团   8.12  1665.01  27023.11  2025年3季度股票投资明细
29  30  600547  山东黄金   8.06   682.22  26831.90  2025年3季度股票投资明细
30  31  601069  西部黄金   7.25   807.32  24138.87  2025年3季度股票投资明细
31  32  000975  山金国际   6.61   964.46  22018.61  2025年3季度股票投资明细
32  33  601899  紫金矿业   9.79  1037.30  35755.72  2025年4季度股票投资明细
33  34  600489  中金黄金   9.09  1421.19  33198.95  2025年4季度股票投资明细
34  35  000975  山金国际   9.01  1352.70  32911.14  2025年4季度股票投资明细
35  36  600988  赤峰黄金   8.79  1027.19  32089.57  2025年4季度股票投资明细
36  37  000426  兴业银锡   8.09   830.44  29563.67  2025年4季度股票投资明细
37  38  600961  株冶集团   8.04  1823.64  29360.60  2025年4季度股票投资明细
38  39  601069  西部黄金   7.91  1083.36  28904.05  2025年4季度股票投资明细
39  40  002155  湖南黄金   7.75  1342.03  28303.40  2025年4季度股票投资明细
40  41  000506  招金黄金   7.70  2154.47  28137.38  2025年4季度股票投资明细
41  42  600547  山东黄金   7.12   672.27  26023.43  2025年4季度股票投资明细
42  43  000603  盛达资源   5.08   599.47  18559.71  2025年4季度股票投资明细
43  44  600711  盛屯矿业   2.85   686.36  10405.22  2025年4季度股票投资明细
44  45  300139  晓程科技   0.94   113.45   3444.34  2025年4季度股票投资明细

In [41]:
pd1 = ak.fund_portfolio_industry_allocation_em(symbol="002207", date="2025")

In [42]:
pd1[pd1['截止时间'] > '2025-06-30'][['行业类别', '占净值比例', '截止时间']]

  行业类别  占净值比例        截止时间
0  采矿业  84.13  2025-12-31
1  制造业   8.04  2025-12-31
2  采矿业  83.86  2025-09-30
3  制造业   9.63  2025-09-30

In [32]:
ak.fund_individual_achievement_xq(symbol='002207')

    业绩类型    周期     本产品区间收益  本产品最大回撒   周期收益同类排名
0   年度业绩  成立以来  188.300000    49.55   294/2145
1   年度业绩  今年以来   15.412330    33.44    62/2145
2   年度业绩  2025   86.700000    16.49    49/2142
3   年度业绩  2024    2.840000    22.63  1204/2138
4   年度业绩  2023    7.880000    18.09    71/2125
5   年度业绩  2022    4.150000    19.95    49/2021
6   年度业绩  2021   -3.740000    17.98  1667/1909
7   年度业绩  2020   14.790000    22.48  1437/1778
8   年度业绩  2019   28.910000    19.14   787/1679
9   年度业绩  2018  -15.400000    31.46   820/1566
10  年度业绩  2017  -15.780000    21.94  1300/1316
11  年度业绩  2016   13.530000    22.81    23/1035
12  年度业绩  2015    0.200000      NaN    509/624
13  阶段业绩   近1月  -14.830133      NaN  2083/2145
14  阶段业绩   近3月   15.412330    33.44    61/2142
15  阶段业绩   近6月   18.349754    33.44    86/2134
16  阶段业绩   近1年   74.199396    33.44    99/2105
17  阶段业绩   近3年  103.028169    33.44    36/1930
18  阶段业绩   近5年  148.534483    33.44    31/1696

In [34]:
ak.fund_open_fund_daily_em()

,基金代码,基金简称,2026-04-02-单位净值,2026-04-02-累计净值,2026-04-01-单位净值,2026-04-01-累计净值,日增长值,日增长率,申购状态,赎回状态,手续费
0,023144,汇添富中证油气资源ETF发起式联接A,1.5731,1.5731,1.5157,1.5157,0.0574,3.79,开放申购,开放赎回,0.10%
1,023145,汇添富中证油气资源ETF发起式联接C,1.5705,1.5705,1.5132,1.5132,0.0573,3.79,开放申购,开放赎回,0.00%
2,021855,博时中证油气资源ETF发起式联接A,1.4124,1.4124,1.3623,1.3623,0.0501,3.68,限大额,开放赎回,0.10%
3,021856,博时中证油气资源ETF发起式联接C,1.4081,1.4081,1.3581,1.3581,0.05,3.68,限大额,开放赎回,0.00%
4,008425,国联品牌优选混合C,0.5792,0.5792,0.5593,0.5593,0.0199,3.56,开放申购,开放赎回,0.00%
...,...,...,...,...,...,...,...,...,...,...,...
22987,026934,鑫元周期睿选混合发起式C,,,,,,,暂停申购,暂停赎回,0.00%
22988,026933,鑫元周期睿选混合发起式A,,,,,,,暂停申购,暂停赎回,0.08%
22989,026677,创金合信弘达债券C,,,,,,,封闭期,封闭期,0.00%
22990,026676,创金合信弘达债券A,,,,,,,封闭期,封闭期,0.03%
22991,026705,方正富邦恒信双利债券A,,,,,,,暂停申购,暂停赎回,0.03%

In [47]:
ak.fund_open_fund_rank_em()

,序号,基金代码,基金简称,日期,单位净值,累计净值,日增长率,近1周,近1月,近3月,近6月,近1年,近2年,近3年,今年来,成立来,自定义,手续费
0,1,022364,永赢科技智选混合发起A,2026-04-02,3.8018,3.8018,-1.71,0.02,-3.69,0.59,13.84,204.07,NaN,NaN,0.59,280.18,210.12320,0.15%
1,2,022365,永赢科技智选混合发起C,2026-04-02,3.7687,3.7687,-1.71,0.01,-3.74,0.44,13.50,202.15,NaN,NaN,0.44,276.87,208.17730,0.00%
2,3,011369,华商均衡成长混合A,2026-04-02,2.5514,2.5514,-0.99,2.59,4.90,29.56,53.77,195.71,243.72,161.17,29.56,155.14,200.97910,0.15%
3,4,011370,华商均衡成长混合C,2026-04-02,2.4765,2.4765,-1.00,2.58,4.85,29.37,53.32,193.98,239.67,156.55,29.37,147.65,199.20260,0.00%
4,5,008528,华泰柏瑞质量成长A,2026-04-02,2.2263,2.2263,-1.59,-0.08,0.45,25.20,44.32,193.90,188.01,118.01,25.20,122.63,204.01470,0.15%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16666,16667,025308,国泰海通中证全指指数增强A,2026-04-02,1.0483,1.0483,-1.20,0.58,-5.75,3.52,NaN,NaN,NaN,NaN,3.52,4.83,4.83000,0.12%
16667,16668,023679,格林上证科创板综合指数增强A,2026-04-02,1.0001,1.0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.01,0.01000,0.03%
16668,16669,026970,泓德裕康债券D,2026-04-02,1.3956,1.3956,-0.31,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.27,-1.26636,0.03%
16669,16670,025046,永赢元享稳健多资产90天持有混合发起(FOF)A,2026-03-31,1.0287,1.0287,-0.26,0.20,-1.24,1.91,NaN,NaN,NaN,NaN,1.91,2.87,NaN,0.80%
16670,16671,024193,国投瑞银中证全指公用事业ETF发起式联接C,2026-04-02,1.0643,1.0643,-0.44,-5.81,-0.88,6.30,6.36,NaN,NaN,NaN,6.30,6.43,6.43000,0.00%